/**
 * LondonPlan RAG API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceEnum } from './serviceEnum';
import { HealthDependencies } from './healthDependencies';


export interface HealthResponse {
    service: ServiceEnum;
    time: string;
    correlation_id: string | null;
    dependencies: HealthDependencies;
}
