/**
 * LondonPlan RAG API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DependencyHealth } from './dependencyHealth';


export interface HealthDependencies {
    database: DependencyHealth;
    redis: DependencyHealth;
}
