/**
 * LondonPlan RAG API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `londonplan-api` - londonplan-api
 */
export enum ServiceEnum {

    LondonplanApi = 'londonplan-api'
}
