/**
 * LondonPlan RAG API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HealthResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     *
     *
     * @endpoint get /api/health/
*/
    healthRetrieve(extraHttpRequestParams?: any): Observable<HealthResponse>;

}
